name: flutter_palette
description: >-
  A package for creating, generating, and interfacing with color palettes.
  With support for constructing colors in the CMYK, HSI, HSL, HSP, HSB, LAB,
  RGB, and XYZ color spaces.
version: 0.2.0
homepage: https://github.com/james-alex/flutter_palette

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_color_models: ^0.3.3+1
  palette: ^0.2.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
